[package]
name = "ic-kit"
version = "0.3.0"
authors = ["Parsa Ghadimi <parsa@fleek.co>"]
edition = "2018"

[dependencies]
ic-cdk = "0.3.0"
ic-cdk-macros = "0.3.0"
serde = { version="1.0.130", features = ["derive"] }
serde_bytes = "0.11"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-std = { version="1.9.0", features = ["attributes"] }