[package]
name = "ic-kit"
version = "0.3.0"
authors = ["Parsa Ghadimi <parsa@fleek.co>"]
edition = "2018"

[dependencies]
ic-cdk = "0.3.0"
serde = "1.0.130"
async-std = { version="1.9.0", features = ["attributes"] }